[package]
name = "bxt-rs"
version = "1.0.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.3.2"
libc = "0.2.99"
libloading = "0.7.0"
log = "0.4.14"
serde_json = "1.0.66"
serde = "1.0.127"
bxt-macros = { path = "bxt-macros" }
bxt-patterns = { path = "bxt-patterns" }
bxt-strafe = { path = "bxt-strafe" }
simplelog = "0.10.0"
color-eyre = { version = "0.5.11", default-features = false }
once_cell = "1.8.0"
ash = "0.33.0"
rust_hawktracer = "0.7.0"
thiserror = "1.0.26"
byte-slice-cast = "1.0.0"
crossbeam-channel = "0.5.1"
git-version = "0.3.5"
hltas = "0.5.0"
glam = "0.20.2"
rand = "0.8.4"
genevo = "0.7.0"
parking_lot = "0.11.2"

[target."cfg(windows)".dependencies.simplelog]
version = "0.10.0"
default-features = false

[target."cfg(windows)".dependencies]
minhook-sys = "0.1.1"

[target."cfg(windows)".dependencies.winapi]
version = "0.3.9"
features = ["libloaderapi", "psapi", "winuser", "synchapi", "handleapi", "processthreadsapi"]

[profile.dev.package.bxt-patterns]
opt-level = 3

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = 1 # For lines in backtraces.

[workspace]
members = [".", "bxt-macros", "bxt-patterns", "bxt-strafe"]

[build-dependencies]
gl_generator = "0.14.0"

[features]
vulkan-debug = []
profiling = ["rust_hawktracer/profiling_enabled"]
